{{- if .Values.imagePullSecrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecrets.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  .dockerconfigjson: {{ required "imagePullSecrets.dockerconfigjson is required when imagePullSecrets.create=true" .Values.imagePullSecrets.dockerconfigjson | quote }}
type: kubernetes.io/dockerconfigjson
{{- end }}
