# This file is intentionally left empty
# Helm creates the target namespace when --create-namespace is specified.
# Example: helm install cinemaabyss ./src/kubernetes/helm --namespace cinemaabyss --create-namespace
